#!/bin/bash -e

function setup {
    echo "$0> Setting up test harness"
    HTTP_PORT=$(get-unused-tcp-port)
    echo "$0> Using HTTP port $HTTP_PORT"

    echo "$0> Starting system test server as a background process"
    java -jar target/system-test-server.jar $HTTP_PORT &
    SERVER_PID=$!
    echo "$0> Server PID: $SERVER_PID"

    SERVER_URL="http://localhost:${HTTP_PORT}/"
    echo "$0> Server URL: $SERVER_URL"

    wait-for-http-response $SERVER_URL
}

function teardown {
    echo "$0> Tearing down test harness"
    strangle $SERVER_PID
}


echo
echo "Session state is persisted across requests?"
echo "########################################################################"

setup

echo TODO execute some tests here

teardown


echo
echo "Session state is persisted, even though the server process is restarted?"
echo "########################################################################"

echo TODO


exit 0
