#!/bin/bash -e

echo
echo "Session state is persisted across requests?"
echo "########################################################################"

HTTP_PORT=$(get-unused-tcp-port)
echo "$0> Using HTTP port $HTTP_PORT"

echo "$0> Starting system test server"
java -jar target/system-test-server.jar $HTTP_PORT &
SERVER_PID=$!
echo "$0> Server PID: $SERVER_PID"

wait-for-http-response http://localhost:${HTTP_PORT}/

echo TODO execute some tests here

strangle $SERVER_PID


echo
echo "Session state is persisted, even though the server process is restarted?"
echo "########################################################################"

echo TODO


exit 0
