#!/bin/bash -e

# OPTIONS
#########

CURL_COOKIE_JAR=target/curl-cookie-jar.txt


# FUNCTIONS
###########

function log {
    echo "$0> $@"
}

function setup {
    log "Setting up test harness"

    log "Emptying the curl cookie jar"
    echo > $CURL_COOKIE_JAR

    HTTP_PORT=$(get-unused-tcp-port)
    log "Using HTTP port $HTTP_PORT"

    log "Starting system test server as a background process"
    java -jar target/system-test-server.jar $HTTP_PORT &
    SERVER_PID=$!
    log "Server PID: $SERVER_PID"

    SERVER_URL="http://localhost:${HTTP_PORT}/"
    log "Server URL: $SERVER_URL"

    wait-for-http-response $SERVER_URL
    log "Test harness done"
    echo; echo
}

function teardown {
    echo; echo
    log "Tearing down test harness"
    strangle $SERVER_PID
    log "Teardown done"
}

function failfast {
    log "TEST FAILED"
    teardown
    exit 1
}


# TESTS
#######

echo
echo "Session state is persisted across requests?"
echo "########################################################################"

setup
http get $SERVER_URL and_in_response_expect "{}" || failfast
http post "data expected to be stored in the session" $SERVER_URL || failfast
http get $SERVER_URL and_in_response_expect "data expected to be stored in the session" || failfast
teardown

echo
echo "Session state is persisted, even though the server process is restarted?"
echo "########################################################################"

echo TODO

exit 0
